### PR TITLE
ci: setup prettier lint

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes:

- Added lint(prettier) job to build.yml

- Ref: #129

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
needs deconflicting

**Comment by viceice** [comment]
prettier is already called via `yarn test`, so i don't think we need extra job

**Comment by RahulGautamSingh** [comment]
> prettier is already called via `yarn test`, so i don't think we need extra job

Had the same doubt..

**Review by viceice — COMMENTED** [review]
No, i don't think we need to update the ci, as it already runs prettier. we should add a `script` to run prettier fix locally and perhaps husky and pretty-quick on pre-commit hook, see main repo for sample

**Comment by RahulGautamSingh** [comment]
> No, i don't think we need to update the ci, as it already runs prettier. we should add a `script` to run prettier fix locally and perhaps husky and pretty-quick on pre-commit hook, see main repo for sample

prettier-fix is already therein the scripts. I will look into husky and pre-commit hook implementation.👍

**Comment by viceice** [comment]
Closing this, as it's not what we need

**Pull request closed without merging**
